---
# tasks file for while_true_do.sys_aide

- name: Initialize AIDE DB
  command: "aide --init"
  changed_when: true
  become: true
  tags:
    - aide
    - initialization
    - security
    - system

- name: Move AIDE DB
  copy:
    src: "{{ wtd_sys_aide_conf_db_path }}/{{ wtd_sys_aide_conf_db_new_name }}"
    dest: "{{ wtd_sys_aide_conf_db_path }}/{{ wtd_sys_aide_conf_db_name }}"
    backup: true
    remote_src: true
  become: true
  tags:
    - aide
    - initialization
    - security
    - system
