---
# tasks file for while_true_do.sys_aide

- name: Manage AIDE Check Service File
  template:
    src: "aide-check.service.j2"
    dest: "/etc/systemd/system/aide-check.service"
    owner: "root"
    group: "root"
    mode: "0644"
  become: true
  tags:
    - aide
    - compliance
    - security
    - service
    - system
    - timer

- name: Manage AIDE Check Timer File
  template:
    src: "aide-check.timer.j2"
    dest: "/etc/systemd/system/aide-check.timer"
    owner: "root"
    group: "root"
    mode: "0644"
  become: true
  tags:
    - aide
    - compliance
    - security
    - service
    - system
    - timer

- name: Manage AIDE Check Timer
  systemd:
    name: "aide-check.timer"
    state: "started"
    enabled: true
    daemon_reload: true
  become: true
  tags:
    - aide
    - compliance
    - security
    - service
    - system
    - timer
